experiment:
    project: "titok_s_128_stage3"
    name: "titok_s_128_stage3_run1"
    output_dir: "exp/titok_s_128_stage3_laion_run1"
    max_train_examples: 51775594
    save_every: 20_000
    eval_every: 5000
    generate_every: 5000
    log_every: 50
    log_grad_norm_every: 1_000
    resume: True
    init_weight: ""

model:
    vq_model:
        codebook_size: 4096
        token_size: 12
        use_l2_norm: True
        commitment_cost: 0.25
        # vit arch
        vit_enc_model_size: "small"
        vit_dec_model_size: "small"
        vit_enc_patch_size: 16
        vit_dec_patch_size: 16
        num_latent_tokens: 128
        finetune_decoder: True
        pretrained_tokenizer_weight: "./pretrained_models/maskgit-vqgan-imagenet-f16-256.bin"
    

dataset:
  train:
    target: data.laion.Text2ImageLaion
    params:
      s3_cfg:
        access_key: 'FB7QKWTWP279SQMLBX4H'
        secret_key: 'dN6ph2f9cQcVhnOCngiGKwPUjMqpM9o4oiKM67mb'
        bucket_name: 'public-dataset'
        data_prefix: "laion-coco/meta/"
        endpoint: 'http://p-ceph-norm-outside.pjlab.org.cn'
      mode: "train"
      image_size: 256
  val:
    target: data.laion.Text2ImageLaion
    params:
      s3_cfg:
        access_key: 'FB7QKWTWP279SQMLBX4H'
        secret_key: 'dN6ph2f9cQcVhnOCngiGKwPUjMqpM9o4oiKM67mb'
        bucket_name: 'public-dataset'
        data_prefix: "laion-coco/meta/"
        endpoint: 'http://p-ceph-norm-outside.pjlab.org.cn'
      mode: "val"
      image_size: 256


training:
    gradient_accumulation_steps: 1
    per_gpu_batch_size: 32
    mixed_precision: "fp16"
    enable_tf32: True
    enable_wandb: True
    use_ema: True
    seed: 0
    max_train_steps: 500_000
    num_generated_images: 2
    max_grad_norm: 1.0
