experiment:
    project: "flextitok_s_128_stage2"
    name: "flextitok_s_128_stage2_run1"
    output_dir: "exp/flextitok_s_128_stage2_laion_run1"
    max_train_examples: 51775594
    save_every: 10_000
    eval_every: 5000
    generate_every: 5000
    log_every: 50
    log_grad_norm_every: 1_000
    resume: True
    init_weight: "./exp/flextitok_s_128_stage1_laion_run1/checkpoint-80000/ema_model/pytorch_model.bin"


model:
    vq_model:
        codebook_size: 4096
        token_size: 12
        use_l2_norm: True
        commitment_cost: 0.25
        # vit arch
        vit_enc_model_size: "small"
        vit_dec_model_size: "small"
        vit_enc_patch_size: 16
        vit_dec_patch_size: 16
        num_latent_tokens: 128
        finetune_decoder: True
        pretrained_tokenizer_weight: "./pretrained_models/maskgit-vqgan-imagenet-f16-256.bin"
    
losses:
    discriminator_start: 20_000
    quantizer_weight: 0.0
    discriminator_factor: 1.0
    discriminator_weight: 0.01
    perceptual_loss: "convnext_s"
    perceptual_weight: 0.1
    reconstruction_loss: "l2"
    reconstruction_weight: 1.0
    lecam_regularization_weight: 0.001

dataset:
  train:
    target: data.laion.LaionCOCODataset
    params:
      s3_cfg:
        access_key: 'FB7QKWTWP279SQMLBX4H'
        secret_key: 'dN6ph2f9cQcVhnOCngiGKwPUjMqpM9o4oiKM67mb'
        bucket_name: 'public-dataset'
        data_prefix: "laion-coco/meta/"
        endpoint: 'http://p-ceph-norm-outside.pjlab.org.cn'
      mode: "train"
      image_size: 256
  val:
    target: data.laion.LaionCOCODataset
    params:
      s3_cfg:
        access_key: 'FB7QKWTWP279SQMLBX4H'
        secret_key: 'dN6ph2f9cQcVhnOCngiGKwPUjMqpM9o4oiKM67mb'
        bucket_name: 'public-dataset'
        data_prefix: "laion-coco/meta/"
        endpoint: 'http://p-ceph-norm-outside.pjlab.org.cn'
      mode: "val"
      image_size: 256


optimizer:
    name: adamw 
    params:
        learning_rate: 1e-4
        discriminator_learning_rate: 1e-4
        beta1: 0.9
        beta2: 0.999
        weight_decay: 1e-4

lr_scheduler:
    scheduler: "cosine"
    params:
        learning_rate: ${optimizer.params.learning_rate}
        warmup_steps: 5_000
        end_lr: 1e-5

training:
    gradient_accumulation_steps: 1
    per_gpu_batch_size: 32
    mixed_precision: "fp16"
    enable_tf32: True
    enable_wandb: True
    use_ema: True
    seed: 42
    max_train_steps: 500_000
    num_generated_images: 2
    max_grad_norm: 1.0