experiment:
    project: "llamagen-flex"
    name: "llamagen-flex"
    output_dir: "exp/llamagen-flex"
    max_train_examples: 1_281_167
    save_every: 10000
    eval_every: 5000_000
    generate_every: 500_000
    log_every: 50
    log_grad_norm_every: 1_000
    resume: False
    init_weight: ""
    tokenizer_checkpoint: "pretrained_models/flexrep_s256_stage3_200k_clip.bin"
    generator_checkpoint: "exp/llamagen/checkpoint-500000/unwrapped_model/pytorch_model.bin"

model:
    vq_model:
        codebook_size: 4096
        token_size: 12
        is_legacy: False
        use_l2_norm: True
        commitment_cost: 0.25
        # vit arch
        vit_enc_model_size: "small"
        vit_dec_model_size: "small"
        vit_enc_patch_size: 16
        vit_dec_patch_size: 16
        num_latent_tokens: 256
        finetune_decoder: True
    
    generator:
        hidden_size: 1024
        num_hidden_layers: 24
        num_attention_heads: 16
        intermediate_size: 4096
        dropout: 0.1
        attn_drop: 0.1
        class_label_dropout: 0.1
        image_seq_len: 256
        condition_num_classes: 1000

        # sampling hyper-params for RAR-B
        randomize_temperature: 1.0
        guidance_scale: 16.0
        guidance_scale_pow: 2.75
        use_checkpoint: False # True to save memory

        randomness_anneal_start: 125000 # 200 epoch
        randomness_anneal_end: 187500 # 300 epoch

dataset:
  train:
    target: data.imagenet.ImageNetDataset
    params:
      root: "/mnt/hwfile/ai4earth/wangzidong/datasets/imagenet1k/images/"
      mode: "train"
      image_size: 256
  val:
    target: data.imagenet.ImageNetDataset
    params:
      root: "/mnt/hwfile/ai4earth/wangzidong/datasets/imagenet1k/images/"
      mode: "val"
      image_size: 256


optimizer:
    name: adamw 
    params:
        learning_rate: 2e-4
        beta1: 0.9
        beta2: 0.96
        weight_decay: 0.03


lr_scheduler:
    scheduler: "cosine"
    params:
        learning_rate: ${optimizer.params.learning_rate}
        warmup_steps: 10_000 # 100 epochs with bsz 2048
        end_lr: 1e-5

training:
    gradient_accumulation_steps: 1
    per_gpu_batch_size: 128 # 32 GPU, total batch size 2048
    mixed_precision: "bf16"
    enable_tf32: True
    enable_wandb: True
    use_ema: False
    seed: 0
    max_train_steps: 1_000_000
    max_grad_norm: 1.0